// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlqleaoovpivwwgfpbbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZscWxlYW9vdnBpdnd3Z2ZwYmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzgwMzYsImV4cCI6MjA3MTcxNDAzNn0.QNU1Oi_aBtvv8PvtcFtSYXwuZJZRjMckjTup3TfMoeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});